### ISSUE TITLE
爱奇艺签到失败

### ISSUE THREAD

**Issue by auauauto** [yi-Xu-0100/soulsign-scripts#10]
你好，我即使已经登录了爱奇艺，但还是显示签到失败。大佬可以帮我看看问题出在哪里吗？

Typeerror: Cannot re
ad property'0'of un
defined

细节和日志是这样的
{
"domain":
"www.iqiyi.com",

"url":
"https://www.iqiyi.com/u/accountset",

"message": {},

"errno":
true

}

**Comment by yi-Xu-0100** [comment]
@auauauto 你使用的是哪个版本，我今天更新了到 v1.0.4

如果是前面的版本，重新安装一下试试

**Comment by yi-Xu-0100** [comment]
前面的版本有可能更新链接有误，建议直接删除，然后去推荐中安装最新的版本

**Comment by yi-Xu-0100** [comment]
@auauauto 个人中心签到获取积分和浏览热点获取积分的任务，需要配置一个参数，搞不定。

VIP 签到、 VIP 浏览会员俱乐部任务和抽奖活动均已完成，可测试最新版本 v1.0.7

**Comment by auauauto** [comment]
装1.0.7版本后后确实可以了，情况和你说的一样。感谢大佬。

yi_Xu <notifications@github.com> 于2020年11月12日周四 下午5:14写道：
