### ISSUE TITLE
百度文库页面更新了，脚本失效

### ISSUE THREAD

**Issue by YujiaCheng1996** [yi-Xu-0100/soulsign-scripts#11]
RT

**Comment by yi-Xu-0100** [comment]
@YujiaCheng1996 好像没有这个任务了，我没找到任务了，能给个任务界面的链接吗？

**Comment by yi-Xu-0100** [comment]
@YujiaCheng1996 
我没有找到相关的任务，只能更新脚本，给出改版取消任务的通知。
如果有任何百度文库任务的信息，可以在这里留言。

**Comment by YujiaCheng1996** [comment]
好像是改没了，某度吃枣💊
