### ISSUE TITLE
魂签的爱奇艺签到出错了，麻烦大佬看看怎么回事

### ISSUE THREAD

**Issue by auauauto** [yi-Xu-0100/soulsign-scripts#21]
如图，好像是这几天才出现的。之前一直正常
https://s3.jpg.cm/2021/03/01/0WZWi.png
https://s3.jpg.cm/2021/03/01/0nGJk.png

**Comment by yi-Xu-0100** [comment]
@auauauto 非常高兴居然还有人在用，我这几天试着修复一下，我好久没用了，主要没有会员了。。。😅

**Comment by yi-Xu-0100** [comment]
@auauauto 我发现这个 浏览会员俱乐部的任务官方好像出现错误，我手动也无法完成， 所以没有返回数据，只有成功代码，但是任务没有任何更新。我只能将这里作为跳过。

**Comment by auauauto** [comment]
好的，感谢大佬。一直在用你的签到脚本，非常好用，感谢分享！

yi_Xu <notifications@github.com> 于2021年3月1日周一 下午1:10写道：
