### ISSUE TITLE
脚本怎么弄进服务器全自动签到

### ISSUE THREAD

**Issue by ATK1DEF1** [yi-Xu-0100/soulsign-scripts#30]
脚本怎么弄进服务器全自动签到

**Comment by yi-Xu-0100** [comment]
@ATK1DEF1 这些脚本是由 soulsign 插件的脚本，暂时没有相关的全自动脚本，可以查查其他的脚本仓库。可以试试“云函数”，“签到”等字段查找下有无相关。
