### ISSUE TITLE
签到失败

### ISSUE THREAD

**Issue by 253253a** [yi-Xu-0100/soulsign-scripts#37]
聚创 的  登陆失败   你的邮箱是多少呢？

**Comment by yi-Xu-0100** [comment]
yi_Xu#yixuju.cn #换@

@253253a

**Comment by 253253a** [comment]
发了&nbsp; 麻烦看下



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月17日(星期二) 上午10:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yi-Xu-0100/soulsign-scripts] 签到失败 (#37)





 
yi_Xu#yixuju.cn #换@
 
@253253a
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yi-Xu-0100** [comment]
脚本已更新，主要更换了检查登录部分。我看了下网页，没看到签到的按钮，但是我执行脚本的签到，仍然能够完成。。。个人测试已经没问题了，有问题的话，再重新打开这个 issue。😉

如果没有问题，注意修改密码。😀

**Comment by 253253a** [comment]
谢谢了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月17日(周二) 中午11:00
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yi-Xu-0100/soulsign-scripts] 签到失败 (#37)




 
脚本已更新，主要更换了检查登录部分。我看了下网页，没看到签到的按钮，但是我执行脚本的签到，仍然能够完成。。。个人测试已经没问题了，有问题的话，再重新打开这个 issue。😉
 
如果没有问题，注意修改密码。😀
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
