### ISSUE TITLE
😀 可以帮我完善整合一下我写的 `discuz.k` 咩? 😆

### ISSUE THREAD

**Issue by miiwu** [yi-Xu-0100/soulsign-scripts#4]
我看到你写的 [`迅维网`](https://soulsign.inu1255.cn/scripts/238)，应该能用我写的 [`discuz.k.js`](https://soulsign.inu1255.cn/scripts/229) 来整合一下。

哈哈，我觉得可以。
如果不可以或者用着不舒服，也希望你也可以给我写 [`issue`](https://github.com/miiwu/sspanel.soulsign/issues) 告诉我，我应该怎么改善。

**Comment by yi-Xu-0100** [comment]
ok, 我看了你的脚本仓库，emmm，逻辑有点复杂，不太知道哪里算是模板，我给你提 issue 告诉这个论坛出现的特异点吧
