### ISSUE TITLE
51NB论坛签到脚本 V1.0.1 今天已经签到过，点立即执行，报错，签到失败

### ISSUE THREAD

**Issue by jsxyhyj** [yi-Xu-0100/soulsign-scripts#5]
51NB论坛签到脚本 V1.0.1 今天已经签到过，点立即执行，报错，签到失败。     1.0.0时点立即执行报的是已经签到过。明天再试没签到时 1.0.1的签到

**Comment by jsxyhyj** [comment]
1.0.1 今日没有签到，提示签到失败。

**Comment by yi-Xu-0100** [comment]
@jsxyhyj  抱歉，我昨天没有看到，我升级到了1.0.4，昨天应该升级到了1.0.2了。现在的版本应该没有问题。

**Comment by yi-Xu-0100** [comment]
我注册了账户，个人试验过了，暂时没有问题，如果还是签到失败，麻烦告知一声

**Comment by yi-Xu-0100** [comment]
昨天的版本链接弄错了，如果你没有升级，可以打开编辑看一下，当时的 signurl ，最后是否是 sig ，而不是 sign
我打错了，造成无法签到了……很抱歉

**Comment by yi-Xu-0100** [comment]
https://github.com/yi-Xu-0100/soulsign-scripts/commit/996bda4ede0c93d8f52027fba9abb0d8fabb97ea

昨天更新的记录

**Comment by jsxyhyj** [comment]
@yi-Xu-0100 谢谢，可以了。

**Comment by yi-Xu-0100** [comment]
ok. 其实我今天准备升级一下来着，可以看到签到奖励反馈，等下次插件给你自动更新吧~
