### ISSUE TITLE
wnflb签到 不在线

### ISSUE THREAD

**Issue by jsxyhyj** [yi-Xu-0100/soulsign-scripts#6]
// ==UserScript==
// @name              wnflb论坛
// @namespace         https://soulsign.inu1255.cn/scripts/248
// @version           1.0.0
// @author            j_s_y_j_h
// @loginURL          https://www.wnflb2020.com/member.php?mod=logging&action=login
// @updateURL         https://soulsign.inu1255.cn/script/yi-Xu-0100/wnflb论坛
// @expire            900000
// @domain            wnflb2020.com
// ==/UserScript==

var domainurl = "https://wnflb2020.com/";
var domainurl2 = "https://www.wnflb2020.com/";

exports.run = async function (param) {
    var { data } = await axios.get(domainurl);
    if ((/自动登录/.test(data) && /注册/.test(data))) throw "需要登录";
    if (/已签到/.test(data)) return "重复签到";
    var formhash = /name="formhash" value="([^"]+)/.exec(data)[1];
    
    var sign_url = 'https://www.wnflb2020.com/plugin.php?id=fx_checkin:checkin&formhash={}&{}&infloat=yes&handlekey=fx_checkin&inajax=1&ajaxtarget=fwin_content_fx_checkin'.format(
        formhash, formhash)
    var { data } = await axios.post(signurl);
    var reward = /<div class="c">[\r\s\n]*(.*?)<[\/]?div/.exec(data);
    if (reward && /已经签到/.test(reward[1])) return "重复签到";
    if (reward && /签到成功/.test(reward[1])) return reward[1];
    throw '签到失败';
};

exports.check = async function (param) {
    var { data } = await axios.get(domainurl2 + 'home.php?mod=space');
    return !(/先登录/.test(data));
};

**Comment by jsxyhyj** [comment]
我仿照写了一个。请问检查在线是哪个url？   显示不在线。    
domainurl 加了www会提示 domain配置不正确。

**Comment by yi-Xu-0100** [comment]
`@Domain` 可以指定多个，包含脚本中所有出现的 url 的 domain，你参考的脚本是 [人大经济论坛签到脚本](https://github.com/yi-Xu-0100/soulsign-scripts/blob/main/scripts/bbs.pinggu.org.js) 吗？

在这个脚本中 `domainurl` 是这个脚本的全局变量，在两个方法中 `check` 和 `run` 中都可以作为变量。

一般请求的 url 不会需要两种 `domain`。所以我对链接前面部分做了剥离，后面就是不同页面的后缀。
如果可以，建议使用代码块将整个脚本发来看看。

我访问你的 ` domainurl = "https://wnflb2020.com/";` 它同样会自动跳转到 `domainurl2 = "https://www.wnflb2020.com/";`， 所以感觉没必要设置两个。

欢迎讨论~😀
