### ISSUE TITLE
几鸡签到缺少函数exports.run

### ISSUE THREAD

**Issue by LJDXH** [yi-Xu-0100/soulsign-scripts#63]
几鸡签到输入账户和密码后，导入提醒缺少函数wxports.run，不懂的这些，不知道是否可以修复一下，另外这个网站好像已经不能用了，目前使用的是https://a.luxury/signin这个几鸡网站，是否是将代码里面的j02.space换成a.luxury就可以了呢。

**Comment by yi-Xu-0100** [comment]
@LJDXH 本人不再使用这个，所以不注册账号并继续维护。前面的缺少函数的报错，应该是插件版本不对，如果是商店的话，建议找下压缩包安装，商店的很久没更新了。
