### ISSUE TITLE
天翼云盘签到脚本返回 400 错误

### ISSUE THREAD

**Issue by yi-Xu-0100** [yi-Xu-0100/soulsign-scripts#67]
显示的错误消息：
{ "message": "Request failed with status code 400", "name": "Error", "stack": "Error: Request failed with status code 400\n at createError (webpack-internal:///FtD3:16:15)\n at settle (webpack-internal:///21It:17:12)\n at XMLHttpRequest.handleLoad (webpack-internal:///7GwW:61:7)", "config": { "url": "https://m.cloud.189.cn/userSign.action", "method": "get", "headers": { "Accept": "application/json, text/plain, /", "Host": "m.cloud.189.cn", "Accept-Encoding": "gzip, deflate", "_referer": "https://m.cloud.189.cn/zhuanti/2016/sign/index.jsp?albumBackupOpened=1" }, "transformRequest": [ null ], "transformResponse": [ null ], "timeout": 10000, "xsrfCookieName": "XSRF-TOKEN", "xsrfHeaderName": "X-XSRF-TOKEN", "maxContentLength": -1 } }

不知道是我的问题还是天翼云那边的问题

_Originally posted by @zszczh in https://github.com/inu1255/soulsign-chrome/issues/289

**Comment by yi-Xu-0100** [comment]
@zszczh 你上面这个报错信息是哪个浏览器的脚本报的？edge 吗？ 换成 firefox 的插件，试下如何？

你这个信息是从哪里复制出来的，能截个图吗？我看到他这个是 _referer 而不是 Referer 。

而且我发现我上次（ https://github.com/yi-Xu-0100/soulsign-scripts/blob/4f1443daf469d06dc831a99350569a1a146399fc/scripts/cloud.189.cn.js ）应该是已经修复了，所以现在重复签到，也会判断成功。你可以尝试直接复制最新的脚本尝试

![image](https://user-images.githubusercontent.com/25523606/201238875-65872017-4f4b-45f0-b0ba-6672f2d3b6c6.png)

**Comment by zszczh** [comment]
google浏览器
![2022-11-12_095541](https://user-images.githubusercontent.com/30950457/201451148-a40677f9-85ea-44d3-b96d-78865fe23249.png)
![2022-11-12_095435](https://user-images.githubusercontent.com/30950457/201451151-fe70079c-b003-4a0a-85de-86dc774166e7.png)

**Comment by zszczh** [comment]
图片顺序反了，不好意思。最下面的是第一张，上面的是第二张。

**Comment by zszczh** [comment]
在谷歌浏览器上复制了1.0.7代码运行，还是不行。
![2022-11-12_100936](https://user-images.githubusercontent.com/30950457/201451653-5c6a5969-30df-4d3e-8994-ea7e11a93b9e.png)
在备用的火狐上装了1.0.6，运行成功了。
最近谷歌浏览器自动更新过两次，其他的东西我没动。我的猜想，是不是跟浏览器有关系？

**Comment by yi-Xu-0100** [comment]
@zszczh 你用的是 谷歌商店的版本吗？这个插件作者不在谷歌商店继续更新了，然后使用了自更新的方式，我的建议还是用火狐。不然安装最新版本插件，谷歌浏览器有问题可能。

**Comment by zszczh** [comment]
我这个是自己手动安装的，版本号和github上的一样

**Comment by yi-Xu-0100** [comment]
@zszczh 我没法处理这个问题，也可能是谷歌浏览器升级的安全策略什么的。我后期一直在火狐签到。

暂时关闭这个 issue 了，我没法修复，也可能无法修复。

**Comment by zszczh** [comment]
好的，谢谢
