### ISSUE TITLE
网站访问发生502错误，部分脚本无法正常使用

### ISSUE THREAD

**Issue by a115599663322** [yi-Xu-0100/soulsign-scripts#68]
网站访问发生502，疑似服务器宕机，discuz系列脚本无法使用。

**Comment by yi-Xu-0100** [comment]
我没有设立过网站，也不知道你说的是哪个脚本。👀

**Comment by a115599663322** [comment]
> 我没有设立过网站，也不知道你说的是哪个脚本。👀

不好意思，原来是作者的脚本仓库，已联系作者，叨扰了。
