### ISSUE TITLE
什么值得买签到失败

### ISSUE THREAD

**Issue by Jessire** [yi-Xu-0100/soulsign-scripts#70]
什么值得买web签到提示验证码
<img width="934" alt="image" src="https://user-images.githubusercontent.com/61305123/210040796-a1f78504-7b9f-4978-9143-8d3d8fbff332.png">

**Comment by yi-Xu-0100** [comment]
有的时候需要验证码的话，手动在网页端自己签到下，不然会一直尝试，下次更容易出验证码问题。自己签到完，这个页面也点一下，应该会变成重复签到就不用管。如果第二天还是这样，先关闭脚本，自己签到几天，过几天再开。

我没法处理验证码，所以如果有验证码，就没法修复。我有碰到过需要验证码的情况，但是第二天就消失了。

如果每次都需要验证码，那我也没办法了。

**Comment by yi-Xu-0100** [comment]
好像现在就是有验证码环节，该脚本基本无效了。
