### ISSUE TITLE
大佬能求个爱奇艺vip签到的脚本吗。。。

### ISSUE THREAD

**Issue by eno1016** [yi-Xu-0100/soulsign-scripts#9]
在官方只找到一个别人写的请教脚本，自己照着折腾了半天完全不行。。。
纯小白一个，头都挠秃了。。。
不知道大佬有没有vip，如果需要vip大佬又没有的话愿意给您充一个。。。
求求了T^T

**Comment by yi-Xu-0100** [comment]
额，我后面得空看看吧，但是时间不定，只能算是尝试做一下。

**Comment by eno1016** [comment]
> 额，我后面得空看看吧，但是时间不定，只能算是尝试做一下。

好的好的大佬！！您得空了再帮我看看，非常感谢！！

**Comment by yi-Xu-0100** [comment]
@eno1016 可以测试了，<https://soulsign.inu1255.cn/scripts/290>

今天我签到过了，明天才能确认。

**Comment by eno1016** [comment]
哇这么快！！
测试成功了！！！谢谢神仙大佬！
感谢感谢！！

**Comment by yi-Xu-0100** [comment]
@eno1016 我也验证了一下，确实VIP签到已经完成。我在 V1.0.1 中，更新了个人中心签到，访问热点首页，浏览会员俱乐部，修复 expire 缺失问题，但是暂时无法对新任务的验证是否成功。只是推送到本仓库，等明天验证过了，没什么问题的话，到时候会在官方市场更新。

你可以自行复制内容更新测试，也可以等明天插件自动检测更新。本 issue 暂时关闭，后面如果有使用问题，重新开个就好~
